### ISSUE TITLE
如何获取冰冻，是冰冻 不是冰冻核心

### ISSUE THREAD

**Issue by qq517634644** [Mostlai/HD-TEST#1]
RT

**Comment by qq517634644** [comment]
还卡在纯浊灵体上了 ，咋获取啊

**Comment by Mostlai** [comment]
要获取冰冻你需要投入冷结武器，冷结武器你需要满足  杀伤武器学>=3  冰冻核心>=10，满足之后在E键菜单建造冷结武器并投入。
纯浊灵体在小型战场获取，但是你需要先解锁他，解锁要求为污浊研究和灵体学>=1
详细在Wiki搜索查看
