### ISSUE TITLE
地板空间不足

### ISSUE THREAD

**Issue by anlondon** [Mostlai/HD-TEST#10]
小型研究所的地板空间太少了吧，才100；不知道是不是我的出问题了。

想要升级到冰窖，都要把好多修好的家具拆掉；到后面又得重建

**Comment by anlondon** [comment]
刚更新了冰封窖，说明上说是给50的地板空间，但建造后只有17的地板空间；我是遇到bug了吧；
不然这么点空间真没法继续玩下去了。

**Comment by Mostlai** [comment]
抱歉现在才看到，房子是替换不是新增，所以地板上限不会加这么多。关于地板这个问题，前面是比较缺的，解锁征服之后情况会好转

**Comment by anlondon** [comment]
好的，我这边就正在往解锁征服前进。

另外请问后期是否会完善任务队列的功能呢？我看现在是有任务队列的，但是玩家不能选择自己需要的任务，后期会加入玩家添加任务到任务队列嘛？

**Comment by Mostlai** [comment]
这个是一个梦境相关的升级，在完成这个升级之后，可以选择一个持续类行动作为自己的爱好任务，在空闲的时候自动执行此行动，例如自动连续探索副本，自动连续执行任务

**Comment by Mostlai** [comment]
如果条件允许并且有兴趣不介意的话，可以加入QQ群281738137，在里面问更快一点，github有时候我会漏看邮件
