### ISSUE TITLE
小型战场的纯浊灵体无法获取

### ISSUE THREAD

**Issue by Voimulax** [Mostlai/HD-TEST#3]
一开始获得了一个，然后修炼点了魂魄研究，然后就再也没有获得过了
似乎点了魂魄研究之后，数量没有减少
刷了很久，消息确实显示获得了，但是数量没有增长，以至于我技能那点不了灵能医疗学

**Comment by Mostlai** [comment]
居然漏了一个issue....如果你没有解锁灵体这个资源的话要先去解锁,上限的提高方式是建造流光玻璃瓶
